# DVC PIPELINE CONFIGURATION
# Model: LinearSVC (Final Production Model)

stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    params:
      - data_ingestion.test_size
      - data_ingestion.random_state
      - data_ingestion.stratify
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - data/raw/train.csv
      - data/raw/test.csv
      - src/data/data_preprocessing.py
    params:
      - text_preprocessing.remove_stopwords
      - text_preprocessing.lowercase
      - text_preprocessing.remove_punctuation
      - text_preprocessing.lemmatization
    outs:
      - data/interim/train_processed.csv
      - data/interim/test_processed.csv

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - data/interim/train_processed.csv
      - src/model/model_building.py
    params:
      - model_building.model_type
      - model_building.C
      - model_building.loss
      - model_building.penalty
      - model_building.dual
      - model_building.max_iter
      - model_building.tol
      - model_building.class_weight
      - model_building.random_state
    outs:
      - models/linearsvc_model.pkl
      - models/tfidf_vectorizer.pkl
